### ISSUE TITLE
statusCode must be a positive int

### ISSUE THREAD

**Issue by ushakov-ruslan** [alexandrenicol/aws-lambda-router-wn#3]
Hi. I faced with this issue. I suppose it shouldn't be a string

![image](https://user-images.githubusercontent.com/34264829/51248548-20a6be00-1999-11e9-8154-9d6d7222a686.png)

**Comment by ushakov-ruslan** [comment]
It causes 500 error

**Comment by alexandrenicol** [comment]
Hi @ushakov-ruslan,
I'll have a look at this ASAP. Never had this error before. In the meantime, could you share how the Router is configured in your app.js?

**Comment by ushakov-ruslan** [comment]
Here it is
![image](https://user-images.githubusercontent.com/34264829/51249680-a7a96580-199c-11e9-84cf-4ff1cf30e769.png)

**Comment by alexandrenicol** [comment]
@ushakov-ruslan I've just tested directly on AWS Lambda + API Gateway. Your code actually works on there. Which is why this never came up as an error before (I assume that your are running this outside of AWS). 

However, you are right, statusCode should be a positive string anyway. I'm making the changes at the moment. Once the unit tests have run, I'll check it still works on AWS Lambda+API Gateway, and then I'll publish the new version to NPM. 

I'll let you know when that's done.

**Comment by ushakov-ruslan** [comment]
Thank mate. This is really easy to use and flexible thing. I forgot to say I'm using it locally via AWS SAM Local. But anyway it surely would be better to use int there. Thanks in advance

**Comment by alexandrenicol** [comment]
Ok, done. 
Publish under version 0.10.1

Please test and let me know if it solves your issue, and then I'll close this issue.

**Comment by ushakov-ruslan** [comment]
Great! Works perfect. Thanks!!
